// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/compiler/Scanner_Jflex.flex

package compiler;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Scanner_phase1 {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\5\u0100\1\u0200\1\u0300\1\u0100\5\u0400\1\u0500\1\u0600"+
    "\1\u0700\5\u0100\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00"+
    "\1\u0e00\3\u0100\1\u0f00\17\u0100\1\u1000\165\u0100\1\u0600\1\u0100"+
    "\1\u1100\1\u1200\1\u1300\1\u1400\54\u0100\10\u1500\37\u0100\1\u0a00"+
    "\4\u0100\1\u1600\10\u0100\1\u1700\2\u0100\1\u1800\1\u1900\1\u1400"+
    "\1\u0100\1\u0500\1\u0100\1\u1a00\1\u1700\1\u0900\3\u0100\1\u1300"+
    "\1\u1b00\114\u0100\1\u1c00\1\u1300\153\u0100\1\u1d00\11\u0100\1\u1e00"+
    "\1\u1400\6\u0100\1\u1300\u0f16\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\6"+
    "\1\7\2\0\1\10\1\11\1\0\2\10\1\12\1\13"+
    "\1\10\1\14\1\15\1\16\1\17\11\20\1\0\1\10"+
    "\1\6\1\21\1\6\2\0\1\22\3\23\1\24\1\23"+
    "\2\25\1\26\2\25\1\27\1\25\1\30\1\25\1\31"+
    "\1\25\1\32\5\25\1\33\2\25\1\10\1\0\1\10"+
    "\1\0\1\34\1\0\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\25\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\25\1\54\1\55\1\56\1\57"+
    "\1\60\1\61\1\33\1\62\1\25\1\10\1\63\1\10"+
    "\7\0\1\3\32\0\1\1\u01bf\0\12\64\206\0\12\64"+
    "\306\0\12\64\234\0\12\64\166\0\12\64\140\0\12\64"+
    "\166\0\12\64\106\0\12\64\u0116\0\12\64\106\0\12\64"+
    "\346\0\1\1\u015f\0\12\64\46\0\12\64\u012c\0\12\64"+
    "\200\0\12\64\246\0\12\64\6\0\12\64\266\0\12\64"+
    "\126\0\12\64\206\0\12\64\6\0\12\64\246\0\13\1"+
    "\35\0\2\3\5\0\1\1\57\0\1\1\240\0\1\1"+
    "\u01cf\0\12\64\46\0\12\64\306\0\12\64\26\0\12\64"+
    "\126\0\12\64\u0196\0\12\64\6\0\u0100\65\240\0\12\64"+
    "\206\0\12\64\u012c\0\12\64\200\0\12\64\74\0\12\64"+
    "\220\0\12\64\166\0\12\64\146\0\12\64\206\0\12\64"+
    "\106\0\12\64\266\0\12\64\u0164\0\62\64\100\0\12\64"+
    "\266\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[7936];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\3\1\1\1\3"+
    "\1\1\1\3\2\4\4\5\1\1\15\5\1\1\2\0"+
    "\1\2\2\0\3\5\1\0\12\5\1\3\15\5\1\6"+
    "\2\0\1\4\3\5\2\0\23\5\2\0\1\7\2\5"+
    "\2\0\10\5\1\10\2\5\2\0\7\5\1\0\3\5"+
    "\1\0\2\5";

  private static int [] zzUnpackAction() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\66\0\154\0\242\0\330\0\66\0\u010e"+
    "\0\u0144\0\u017a\0\u01b0\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be"+
    "\0\u02f4\0\u032a\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e"+
    "\0\u04a4\0\u04da\0\u0510\0\u0546\0\u057c\0\u05b2\0\u05e8\0\u061e"+
    "\0\u0654\0\u068a\0\u06c0\0\u06f6\0\u072c\0\u0762\0\u0798\0\u07ce"+
    "\0\u0804\0\u083a\0\u0870\0\u08a6\0\u08dc\0\u0912\0\u0948\0\u097e"+
    "\0\u09b4\0\u09ea\0\u0a20\0\u0252\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8"+
    "\0\u0b2e\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c\0\u0c72\0\u0ca8"+
    "\0\u0cde\0\u0654\0\u0d14\0\u0d4a\0\u072c\0\u0d80\0\u0db6\0\u0dec"+
    "\0\u0e22\0\u0e58\0\u0e8e\0\u0ec4\0\u0efa\0\u0f30\0\u0f66\0\u0f9c"+
    "\0\u0fd2\0\u1008\0\u103e\0\u1074\0\u10aa\0\u10e0\0\u1116\0\u114c"+
    "\0\u1182\0\u11b8\0\u11ee\0\u1224\0\u125a\0\u1290\0\u12c6\0\u12c6"+
    "\0\u12fc\0\u1332\0\u1368\0\u139e\0\u13d4\0\u140a\0\u1440\0\u1476"+
    "\0\u14ac\0\u14e2\0\u1518\0\u154e\0\u0252\0\u1584\0\u15ba\0\u15f0"+
    "\0\u1626\0\u165c\0\u1692\0\u16c8\0\u16fe\0\u1734\0\u176a\0\u17a0"+
    "\0\u17d6\0\u180c\0\u1842\0\u1878\0\u18ae\0\u18e4\0\u191a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\4\1\3\1\5\1\6\1\7\1\10"+
    "\1\5\1\11\1\12\1\7\1\13\1\14\1\15\1\5"+
    "\6\16\1\17\1\20\1\21\1\16\1\22\1\16\1\23"+
    "\1\24\1\25\1\26\1\27\2\16\1\30\3\16\1\31"+
    "\1\16\1\32\1\33\1\34\1\35\1\16\1\36\1\37"+
    "\1\16\1\40\1\15\1\2\70\0\1\3\104\0\1\7"+
    "\44\0\2\41\1\0\1\41\1\0\61\41\11\0\1\7"+
    "\67\0\1\7\5\0\1\7\51\0\1\7\6\0\1\7"+
    "\4\0\1\7\56\0\1\42\3\0\1\43\2\0\1\7"+
    "\61\0\1\44\1\0\1\14\1\15\12\0\1\45\30\0"+
    "\1\15\16\0\1\44\1\0\2\15\43\0\1\15\20\0"+
    "\2\16\1\0\41\16\22\0\2\16\1\0\17\16\1\46"+
    "\21\16\22\0\2\16\1\0\32\16\1\47\6\16\22\0"+
    "\2\16\1\0\17\16\1\50\21\16\37\0\1\51\50\0"+
    "\2\16\1\0\30\16\1\52\1\16\1\53\1\16\1\54"+
    "\4\16\22\0\2\16\1\0\25\16\1\55\2\16\1\56"+
    "\10\16\22\0\2\16\1\0\17\16\1\57\10\16\1\60"+
    "\3\16\1\54\4\16\22\0\2\16\1\0\25\16\1\61"+
    "\13\16\22\0\2\16\1\0\13\16\1\62\14\16\1\63"+
    "\10\16\22\0\2\16\1\0\20\16\1\64\5\16\1\65"+
    "\1\66\4\16\1\67\4\16\22\0\2\16\1\0\17\16"+
    "\1\70\15\16\1\71\3\16\22\0\2\16\1\0\32\16"+
    "\1\72\2\16\1\73\3\16\22\0\2\16\1\0\17\16"+
    "\1\74\21\16\22\0\2\16\1\0\34\16\1\75\4\16"+
    "\22\0\2\16\1\0\22\16\1\76\7\16\1\77\6\16"+
    "\22\0\2\16\1\0\30\16\1\100\10\16\22\0\2\16"+
    "\1\0\22\16\1\101\16\16\66\0\1\7\2\0\2\41"+
    "\1\0\1\41\1\0\2\41\1\102\56\41\12\103\1\0"+
    "\53\103\2\43\3\0\60\43\20\0\2\44\3\0\1\104"+
    "\14\0\1\104\22\0\1\44\20\0\2\105\1\0\3\105"+
    "\10\0\6\105\42\0\2\16\1\0\37\16\1\106\1\16"+
    "\22\0\2\16\1\0\23\16\1\107\15\16\22\0\2\16"+
    "\1\0\13\16\1\110\25\16\45\0\1\111\4\0\1\112"+
    "\35\0\2\16\1\0\30\16\1\113\10\16\22\0\2\16"+
    "\1\0\17\16\1\114\21\16\22\0\2\16\1\0\30\16"+
    "\1\115\10\16\22\0\2\16\1\0\13\16\1\116\25\16"+
    "\22\0\2\16\1\0\27\16\1\117\11\16\22\0\2\16"+
    "\1\0\20\16\1\120\20\16\22\0\2\16\1\0\35\16"+
    "\1\121\3\16\22\0\2\16\1\0\33\16\1\122\5\16"+
    "\22\0\2\16\1\0\25\16\1\123\13\16\22\0\2\16"+
    "\1\0\32\16\1\64\6\16\22\0\2\16\1\0\31\16"+
    "\1\124\7\16\22\0\2\16\1\0\34\16\1\64\4\16"+
    "\22\0\2\16\1\0\30\16\1\125\10\16\22\0\2\16"+
    "\1\0\37\16\1\64\1\16\22\0\2\16\1\0\25\16"+
    "\1\113\13\16\22\0\2\16\1\0\23\16\1\126\15\16"+
    "\22\0\2\16\1\0\14\16\1\127\24\16\22\0\2\16"+
    "\1\0\34\16\1\130\4\16\22\0\2\16\1\0\32\16"+
    "\1\131\6\16\22\0\2\16\1\0\23\16\1\132\15\16"+
    "\22\0\2\16\1\0\35\16\1\133\3\16\22\0\2\16"+
    "\1\0\23\16\1\134\15\16\22\0\2\16\1\0\23\16"+
    "\1\135\15\16\3\0\12\103\1\136\53\103\13\0\2\137"+
    "\2\0\2\140\43\0\1\140\20\0\2\16\1\0\1\141"+
    "\40\16\22\0\2\16\1\0\27\16\1\66\11\16\22\0"+
    "\2\16\1\0\16\16\1\142\22\16\62\0\1\143\53\0"+
    "\1\144\37\0\2\16\1\0\25\16\1\64\13\16\22\0"+
    "\2\16\1\0\13\16\1\145\25\16\22\0\2\16\1\0"+
    "\23\16\1\64\15\16\22\0\2\16\1\0\33\16\1\132"+
    "\5\16\22\0\2\16\1\0\34\16\1\146\4\16\22\0"+
    "\2\16\1\0\23\16\1\147\15\16\22\0\2\16\1\0"+
    "\14\16\1\135\24\16\22\0\2\16\1\0\17\16\1\64"+
    "\21\16\22\0\2\16\1\0\33\16\1\133\5\16\22\0"+
    "\2\16\1\0\30\16\1\150\10\16\22\0\2\16\1\0"+
    "\14\16\1\64\1\16\1\64\22\16\22\0\2\16\1\0"+
    "\36\16\1\151\2\16\22\0\2\16\1\0\25\16\1\152"+
    "\13\16\22\0\2\16\1\0\35\16\1\153\3\16\22\0"+
    "\2\16\1\0\23\16\1\154\15\16\22\0\2\16\1\0"+
    "\33\16\1\64\5\16\22\0\2\16\1\0\17\16\1\155"+
    "\21\16\22\0\2\16\1\0\16\16\1\64\22\16\22\0"+
    "\2\16\1\0\25\16\1\122\13\16\3\0\12\103\1\136"+
    "\3\103\1\3\47\103\17\0\2\140\43\0\1\140\20\0"+
    "\2\16\1\0\32\16\1\156\6\16\22\0\2\16\1\0"+
    "\4\16\1\157\1\120\33\16\54\0\1\160\65\0\1\161"+
    "\33\0\2\16\1\0\24\16\1\64\14\16\22\0\2\16"+
    "\1\0\23\16\1\162\15\16\22\0\2\16\1\0\27\16"+
    "\1\122\11\16\22\0\2\16\1\0\32\16\1\66\6\16"+
    "\22\0\2\16\1\0\13\16\1\163\25\16\22\0\2\16"+
    "\1\0\23\16\1\164\15\16\22\0\2\16\1\0\32\16"+
    "\1\165\6\16\22\0\2\16\1\0\27\16\1\166\11\16"+
    "\22\0\2\16\1\0\32\16\1\167\6\16\22\0\2\16"+
    "\1\0\27\16\1\170\11\16\42\0\1\171\67\0\1\171"+
    "\43\0\2\16\1\0\27\16\1\172\11\16\22\0\2\16"+
    "\1\0\34\16\1\122\4\16\22\0\2\16\1\0\15\16"+
    "\1\64\23\16\22\0\2\16\1\0\27\16\1\64\11\16"+
    "\22\0\2\16\1\0\21\16\1\64\17\16\22\0\2\16"+
    "\1\0\13\16\1\173\25\16\22\0\2\16\1\0\34\16"+
    "\1\174\4\16\37\0\1\175\50\0\2\16\1\0\35\16"+
    "\1\122\3\16\22\0\2\16\1\0\40\16\1\64\22\0"+
    "\2\16\1\0\17\16\1\176\21\16\37\0\1\7\50\0"+
    "\2\16\1\0\21\16\1\177\17\16\22\0\2\16\1\0"+
    "\17\16\1\63\21\16\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6480];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\31\1\2\0\1\1\2\0"+
    "\3\1\1\0\31\1\2\0\4\1\2\0\23\1\2\0"+
    "\3\1\2\0\13\1\2\0\7\1\1\0\3\1\1\0"+
    "\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
StringBuilder answer=new StringBuilder();
private void handle_key_words(String s){
    answer.append(s+"\n");
}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner_phase1(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public String yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { answer=new StringBuilder();answer.append("error");
            }
            // fall through
          case 9: break;
          case 2:
            { 
            }
            // fall through
          case 10: break;
          case 3:
            { handle_key_words(yytext());
            }
            // fall through
          case 11: break;
          case 4:
            { answer.append("T_INTLITERAL "+yytext()+"\n");
            }
            // fall through
          case 12: break;
          case 5:
            { answer.append("T_ID "+yytext()+"\n");
            }
            // fall through
          case 13: break;
          case 6:
            { answer.append("T_STRINGLITERAL "+yytext()+"\n");
            }
            // fall through
          case 14: break;
          case 7:
            { answer.append("T_DOUBLELITERAL "+yytext()+"\n");
            }
            // fall through
          case 15: break;
          case 8:
            { answer.append("T_BOOLEANLITERAL "+yytext()+"\n");
            }
            // fall through
          case 16: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
